### ISSUE TITLE
Code not up to date/BEPU

### ISSUE THREAD

**Issue by JustinKerbice** [EugenyN/BEPUphysicsMG#1]
Hi,

your code work well either with last release of MonoGame, but, it's a big but, on other side, it would be great to have the latest BEPU release (1.4.0).

(In fact, it would have been great if the first commit, if it is not the case, was unmodified BEPU code itself, so the following commit allow other to see what you've done).

Finally, as I'm interested in MonoGame, I would like to continue and make current BEPU drawers works with MonoGame, so if you could share anything you've learnt making this one, some advices and other, it could be great.

**Comment by EugenyN** [comment]
Hello!

I haven't worked with this code for a long time. The main change is the support for MonoGame math types. I will look at the latest version of BepuPhysics on Monday.

**Comment by JustinKerbice** [comment]
ok, to avoid loss of time, I just rebuild the dev version of MonoGame Framework, try a simple BEPU example with ModelDrawer and it's work out of the box ! (with latest official release, 3.4, it failed with a missing SetVertexBuffer, fixed as explained in https://github.com/mono/MonoGame/pull/4195).

It needs more work on this, like at least have all demos working with MonoGame, but it looks like to be on the right track :).

**Comment by EugenyN** [comment]
I've updated the code to the latest version of bepu. Added BEPUphysics Drawer which works correctly for me. Thanks for useful link!
